import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import NavBar from "@/components/Navbars";
import Footer from "../../components/Footer";
import Breadcrumb from "@/components/Filepath"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default:"ZumaJobs",
   template: '%s | first app',
  },


   description: "Generated by create next app",
icons: {
  icon: "/fola_edited.jpg"
}
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable}  `}
      >
        
          
          
          <Breadcrumb/>
           {children}
           
        
          
      </body>
    </html>
  );
}
